### ISSUE TITLE
Проблемы с кешированием ресурсов

### ISSUE THREAD

**Issue by nixart-pro** [kudashevs/LastModified#1]
Возникла проблема с кешированием ресурсов на сайте, кеш страниц удалялся только после пересохранения ресурса(хотя отметка кеширования у ресурса снята). Полная очистка кеша сайта перестала сбрасывать кеш страниц. После длительного танцебубна, решением стало - удаление вашего плагина.
ModX-2.7.1., плагин 1.0.8
P.S. Проблема была в новом контексте, не в web(в web не проверял).

**Comment by kudashevs** [comment]
Можно несколько уточнений:

- Какой кеш имеется ввиду, файловый в папке cache/ или браузерный?
- Как проверялось, что кеш не удаляется?
- Если файловый кеш, то как его удаляли, через админку (в меню админки)?
- Полная очистка кеша сайта, это удаление в админке (в меню) или руками папку вычищали?

**Comment by kudashevs** [comment]
Спасибо за наводку, нашел проблему. Сейчас выложу обновление.
Если не сложно можете обновиться и посмотреть, ушла ли проблема или нет?

**Comment by nixart-pro** [comment]
Кеш удалялся через админку, проверялось просто, после редактирования шаблона ресурса, на сайте отображалась старая версия страницы.
Удалил старую версию плагина, поставил новую, проблема осталась.
 
_Еще заметил проблемы с кешированием контекстов, но не факт, что это из-за вашего плагина(он был удален в этот момент). Решилось очисткой кеша - удалением содержимого папки cache._

**Comment by kudashevs** [comment]
Папку кеш после обновления плагина не пробовали удалять полностью? Потому что в теории, там просто нечему срабатывать а админке.

Если есть время, напишите пожалуйста на мою почту, попрошу сделать пару изменений в коде плагина на проблемной машине, попробуем разобраться :)

**Comment by kudashevs** [comment]
Не до конца понятно решилась проблема или нет, больше похоже что да. Закрываю.
Уважаемый @nixart-pro если вдруг какие-то еще проблемы, открывайте новый.
