### ISSUE TITLE
Проблемы с кешированием ресурсов

### ISSUE THREAD

**Issue by TITAN-UZ** [kudashevs/LastModified#2]
Возникла проблема с кешированием ресурсов на сайте, кеш страниц удалялся только после пересохранения ресурса(хотя отметка кеширования у ресурса снята). Полная очистка кеша сайта перестала сбрасывать кеш страниц. После длительного танцебубна, решением стало - удаление вашего плагина.

MODX 2.7.2  LastModified 1.0.9-pl

Тот же проблема кеш Memcached + Filecache после установки не работал кэш в других устройствах или работает с помехами тупо замедляется сайт

**Comment by kudashevs** [comment]
Добрый день,

Несколько уточнений пожалуйста:
- Версия PHP на которой обнаружено подобное поведение?
- Есть ли какая-нибудь информация в логах с пометкой "LastModified: "?
- Полная очистка кеша сайта, это удаление в админке (в меню) или руками папку вычищали?

**Comment by TITAN-UZ** [comment]
PHP 7.0
LOG чист
Удаления через админки не помогает

**Comment by kudashevs** [comment]
Полностью перебрал проект. Для всех документов в иерархии, время которых изменяется, добавил принудительное удаление кеша (в случае если очистка кеша на документе выключена). Проверяйте, все должно работать на 100%.
