### ISSUE TITLE
не отдаёт Last-Modified

### ISSUE THREAD

**Issue by modx-lab** [kudashevs/LastModified#4]
версия 2.8.4, заголовок не отдаёт совсем.
версия пхп 7.4

**Comment by kudashevs** [comment]
Добрый день, @modx-dev 

У меня на чистой установке 2.8.4 отдает без каких либо проблем.
![image](https://user-images.githubusercontent.com/15892462/205592636-77a7976e-ed36-4bdf-b8da-22357dae40c8.png)

Можно пожалуйста предоставить больше информации. Что значит не отдает совсем? Как устанавливали плагин, как настраивали (если настраивали), какие плагины установлены и какие используют событие `OnWebPagePrerender`.

**Comment by modx-lab** [comment]
Наверное это приложение polylang, грешу на него

**Comment by kudashevs** [comment]
Это приложение платное, поэтому потестировать его к сожалению не могу.

Так как проблема похоже не в Last-Modified плагине, то issue я пока закрываю.
Если все же выяснится, что проблема в плагине, открывайте новый issue.

**Comment by modx-lab** [comment]
я могу дать доступ, посмотрите

**Comment by kudashevs** [comment]
Спасибо, но нет @modx-dev. MODx мне уже несколько лет не интересен.

Попробуйте разобраться самостоятельно, это будет полезно. Ничего сложного в этой проблеме нет.
Воспользуйтесь xDebug или посмотрите var_dump'ами где обрывается отдача ответа.

Насколько помню можно скидывать результаты var_dump() прямо в лог:
```
ob_start();
var_dump($variable1, $variable2);
$contents = ob_get_contents();
ob_end_clean();
error_log(print_r($contents."\n",1), 3, $modx->getOption(xPDO::OPT_CACHE_PATH).'logs/error.log');
```

**Comment by modx-lab** [comment]
методом поисков выяснилось, что не работает в связке с minishop2 3.0.5\3.0.7

**Comment by kudashevs** [comment]
Да. точно. Он не работает с `minishop` когда тот устанавливает сессию.

Там в настройках есть опция `lastmodified.prevent_session`.
Посмотрите пожалуйста, какое значение сейчас в ней установлено?

**Comment by modx-lab** [comment]
Сейчас никакого , пустая настройка.

До этого по дефолту был minishop2 session

**Comment by kudashevs** [comment]
Надо обратно вернуть `minishop2` иначе перестанет работать корзина.

Напишите мне пожалуйста на почту `kudashevs@gmail.com`.

**Comment by kudashevs** [comment]
Никаких багов выявлено не было. Однако было принятно решение смахнуть пыль с приложения (выпущен [релиз](https://github.com/kudashevs/LastModified/releases/tag/1.1.1-pl)).
Плюс обновил документацию, чтобы было понятно, для чего используется `prevent_session`.
